"""
AEP IR LLM Generability Experiment Runner

Three modes of operation:

1. Default (python runner.py):
   Builds 30 pipeline inputs (prompt.md + task) in pipeline/ for the human+coder flow

2. Validate (python runner.py validate):
   Batch-validates all output-plan.json files generated by the coder,
   wraps in envelopes, runs validator, and produces CSV report

3. Test envelope (python runner.py --test-envelope <file>):
   Tests envelope creation from a raw plan (Fase 5)

Flow:
    python runner.py                    # Step 1: generate 30 inputs
    # Human: instructs coder locally to process each input-coder.md -> output-plan.json
    python runner.py validate           # Step 3: batch-validate all outputs -> CSV
"""

import json
import os
import sys
import glob
import re
import hashlib
import subprocess
from pathlib import Path
from typing import Dict, List, Optional, Set

try:
    from canonicaljson import encode_canonical_json
except ImportError:
    # Fallback: simple canonicalization without RFC 8785
    def encode_canonical_json(obj):
        return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")

# Add parent to path for validator import
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

BASE_DIR = Path(__file__).parent.resolve()
TASKS_DIR = BASE_DIR / "tasks"
PROMPT_FILE = BASE_DIR / "prompt.md"
PIPELINE_DIR = BASE_DIR / "pipeline"
RESULTS_DIR = BASE_DIR / ".." / ".." / "experiment-results"
VALIDATOR_SCRIPT = BASE_DIR / "validator.py"

# ── Envelope Creation (Fase 5 — kept unchanged) ─────────────────


def create_envelope(plan_dict: Dict) -> Dict:
    """
    Wrap a plan in an envelope with checksum per SPEC/AEP-IR-1.0.md §6.2.

    The LLM generates only the plan (plan_header + nodes + edges).
    The runner adds the envelope (canonical plan + SHA256 checksum).
    """
    canonical_bytes = encode_canonical_json(plan_dict)
    checksum = hashlib.sha256(canonical_bytes).hexdigest()
    envelope = {
        "plan": json.loads(canonical_bytes.decode("utf-8")),
        "checksum": checksum,
    }
    return envelope


# ── Verdict Classification ──────────────────────────────────────

SPEC_FIXABLE_ERRORS = {"OR-1", "DAG-1"}

PROMPT_FIXABLE_ERRORS = {"CR-2", "TEC-1", "PH-3", "N-5", "BR-2"}


def classify_verdict(error_categories: Set[str]) -> str:
    """Classify errors as spec-fixable or prompt-fixable"""
    if not error_categories:
        return "pass"

    if error_categories & SPEC_FIXABLE_ERRORS:
        return "spec-fixable"
    else:
        return "prompt-fixable"


# ── Pipeline Builder (Default Mode) ────────────────────────────


def build_pipeline():
    """
    Gera 30 pastas com input-coder.md (prompt + tarefa mesclados)

    Estrutura:
        pipeline/
        +-- tarefa-01-gen-01/
        |   +-- input-coder.md
        +-- tarefa-01-gen-02/
        |   +-- input-coder.md
        ... ate tarefa-10-gen-03
    """
    PIPELINE_DIR.mkdir(parents=True, exist_ok=True)

    # Load prompt base
    with open(PROMPT_FILE, "r", encoding="utf-8") as f:
        prompt_base = f.read()

    # Find task files
    task_files = sorted(glob.glob(str(TASKS_DIR / "*.md")))
    if not task_files:
        print(f"[ERRO] Nenhum arquivo de tarefa encontrado em: {TASKS_DIR}")
        sys.exit(1)

    for filepath in task_files:
        task_path = Path(filepath)
        # Extract task number from filename (e.g., "01-monitor-data-privacy-legislation.md" -> "01")
        stem = task_path.stem
        task_num = stem.split("-")[0]

        with open(filepath, "r", encoding="utf-8") as f:
            task_content = f.read()

        for gen in range(1, 4):
            folder_name = f"tarefa-{task_num}-gen-{gen:02d}"
            target_folder = PIPELINE_DIR / folder_name
            target_folder.mkdir(exist_ok=True)

            # Merge prompt + task
            input_content = (
                f"{prompt_base}\n\n"
                f"---\n\n"
                f"### TAREFA A SER EXECUTADA:\n\n"
                f"{task_content}\n\n"
                f"---\n\n"
                f"**INSTRUCAO FINAL**: Retorne APENAS o JSON puro do plano "
                f"(plan_header + nodes + edges).\n"
                f"NAO inclua checksum. NAo envolva em envelope. "
                f"O checksum sera calculado externamente."
            )

            with open(target_folder / "input-coder.md", "w", encoding="utf-8") as f:
                f.write(input_content)

    # Count generated inputs
    input_count = len(list(PIPELINE_DIR.glob("**/input-coder.md")))
    print(f"[OK] Pipeline gerado! {input_count} inputs criados em: {PIPELINE_DIR}")
    print("")
    print("Proximo passo: Peça ao seu Coder para ler o 'input-coder.md' de cada pasta")
    print("e salvar o resultado como 'output-plan.json' na mesma pasta.")
    print("")
    print("Exemplo de instrução para o Coder:")
    print('  "Leia tools/aep-ir-validator/pipeline/tarefa-01-gen-01/input-coder.md')
    print('   e salve a resposta como tools/aep-ir-validator/pipeline/tarefa-01-gen-01/output-plan.json"')
    print("")
    print("Apos preencher todas as pastas, execute:")
    print("  python tools/aep-ir-validator/runner.py validate")


# ── Batch Validator (Validate Mode) ────────────────────────────


def validate_results():
    """
    Valida todos os output-plan.json gerados pelo coder.

    Para cada pasta em pipeline/:
      1. Ler output-plan.json (plan puro, sem envelope)
      2. Chamar create_envelope() para envelopar
      3. Salvar envelope temporario
      4. Rodar validator.py contra o envelope
      5. Capturar erros e classificar verdict
      6. Escrever linha no CSV
    """
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    csv_path = RESULTS_DIR / "results-table.csv"

    # Write CSV header
    with open(csv_path, "w", encoding="utf-8") as csv:
        csv.write("plan_id,task,generation,status,error_categories,error_count,verdict,notes\n")

    total_found = 0
    total_valid = 0
    total_invalid = 0

    print("\n" + "=" * 60)
    print("  AEP IR — Validacao em Lote")
    print("=" * 60)

    # Scan pipeline folders
    for folder in sorted(PIPELINE_DIR.iterdir()):
        if not folder.is_dir():
            continue

        # Extract metadata from folder name (e.g., "tarefa-01-gen-01")
        parts = folder.name.split("-")
        if len(parts) < 4:
            continue
        task_num = parts[1]
        gen_str = parts[3]
        plan_id = f"plan-{task_num}-{gen_str}"

        output_json = folder / "output-plan.json"
        if not output_json.exists():
            print(f"  [..] {folder.name}: aguardando output-plan.json")
            continue

        total_found += 1

        # Step 1: read raw plan
        try:
            raw_plan = json.loads(output_json.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            print(f"  [--] {plan_id}: JSON invalido ({e})")
            # Write to CSV as parse error
            with open(csv_path, "a", encoding="utf-8") as csv:
                csv.write(f"{plan_id},{task_num},{gen_str},parse_error,PARSE-ERROR,1,prompt-fixable,JSON malformed: {e}\n")
            continue

        # Step 2: wrap in envelope
        try:
            envelope = create_envelope(raw_plan)
        except Exception as e:
            print(f"  [--] {plan_id}: erro ao envelopar ({e})")
            with open(csv_path, "a", encoding="utf-8") as csv:
                csv.write(f"{plan_id},{task_num},{gen_str},envelope_error,ENV-ERROR,1,prompt-fixable,Envelope creation failed: {e}\n")
            continue

        # Step 3: save temp envelope
        temp_envelope = folder / "envelope-temp.json"
        temp_envelope.write_text(json.dumps(envelope, indent=2), encoding="utf-8")

        # Step 4: also save copy to results dir
        result_json = RESULTS_DIR / f"{plan_id}.json"
        result_json.write_text(json.dumps(envelope, indent=2), encoding="utf-8")

        # Step 5: run validator
        result = subprocess.run(
            ["python", str(VALIDATOR_SCRIPT), str(temp_envelope)],
            capture_output=True,
            text=True,
        )

        # Save validation log
        validation_log = RESULTS_DIR / f"{plan_id}-validation.txt"
        with open(validation_log, "w", encoding="utf-8") as f:
            f.write(result.stdout)
            if result.stderr:
                f.write("\n--- STDERR ---\n" + result.stderr)

        # Step 6: parse validator output to extract error categories
        # Validator output format:
        #   fname  [FAIL] INVALID (1 errors)
        #     -> N-3 [nodes[0]]: 'nodes' array is empty
        #     -> TEC-1 node-002: missing required effects
        error_categories = set()
        if result.returncode != 0 or "INVALID" in result.stdout:
            for line in result.stdout.split("\n"):
                # Match rule codes like "N-3", "TEC-1", "DAG-1" etc.
                # They appear after "-> " in validator output
                rule_matches = re.findall(
                    r"(?:N-|PH-|B-|BR-|E-|DAG-|BU-|CC-|TEC-|CR-|OR-|MC-|ENV-|PARSE-|X-)[0-9]+",
                    line
                )
                for rule in rule_matches:
                    error_categories.add(rule)

        if result.returncode == 0 and "INVALID" not in result.stdout:
            status = "valid"
            verdict = "pass"
            error_count = 0
            print(f"  [OK] {plan_id}: VALIDO")
            total_valid += 1
        else:
            status = "invalid"
            verdict = classify_verdict(error_categories)
            error_count = len(error_categories) if error_categories else 1
            print(f"  [--] {plan_id}: INVALIDO (erros: {sorted(error_categories)})")
            total_invalid += 1

        # Step 7: write CSV line
        with open(csv_path, "a", encoding="utf-8") as csv:
            categories_str = ";".join(sorted(error_categories)) if error_categories else ""
            csv.write(
                f"{plan_id},{task_num},{gen_str},{status},"
                f"{categories_str},{error_count},{verdict},\n"
            )

    # Summary
    print("\n" + "=" * 60)
    print(f"  Resumo da Validacao")
    print("=" * 60)
    print(f"  Total processados: {total_found}")
    print(f"  Validos           : {total_valid}")
    if total_found > 0:
        print(f"  Taxa de aprovacao : {total_valid / total_found * 100:.1f}%")
    print(f"  Invalidos         : {total_invalid}")
    if total_invalid > 0:
        print(f"  Pendentes         : (analisar CSV para detalhes)")
    print("=" * 60)

    print(f"\nTabela de resultados gerada em: {csv_path}")
    print(f"Envelopes salvos em: {RESULTS_DIR}")

    # Return counts for programmatic use
    return total_found, total_valid, total_invalid


# ── Main ───────────────────────────────────────────────────────


def main():
    if len(sys.argv) > 1:

        # ── Validate mode ──
        if sys.argv[1] == "validate":
            validate_results()
            return

        # ── Test envelope mode (Fase 5) ──
        if sys.argv[1] == "--test-envelope":
            test_file = sys.argv[2] if len(sys.argv) > 2 else None
            if not test_file or not os.path.isfile(test_file):
                print(f"[ERRO] Arquivo nao encontrado: {test_file}")
                print("Uso: python runner.py --test-envelope <caminho-para-plan-raw.json>")
                sys.exit(1)

            test_path = Path(test_file)
            try:
                raw_plan = json.loads(test_path.read_text(encoding="utf-8"))
            except json.JSONDecodeError as e:
                print(f"[ERRO] JSON invalido em {test_file}: {e}")
                sys.exit(1)

            envelope = create_envelope(raw_plan)
            print(json.dumps(envelope, indent=2, ensure_ascii=False))
            print(f"\nChecksum: {envelope['checksum']}")

            # Validate the envelope via subprocess
            temp_env = test_path.parent / "_test_envelope_temp.json"
            try:
                temp_env.write_text(json.dumps(envelope, indent=2), encoding="utf-8")
                result = subprocess.run(
                    ["python", str(VALIDATOR_SCRIPT), str(temp_env)],
                    capture_output=True, text=True,
                )
                if result.returncode == 0 and "INVALID" not in result.stdout:
                    print("\n[OK] Validation: PASSED")
                else:
                    print("\n[FAIL] Validation: FAILED")
                    print(result.stdout)
            finally:
                if temp_env.exists():
                    temp_env.unlink()
            return

        # ── Unknown flag ──
        print(f"[ERRO] Flag desconhecida: {sys.argv[1]}")
        print("Uso:")
        print("  python runner.py                    # Gerar pipeline (30 inputs)")
        print("  python runner.py validate           # Validar outputs do coder")
        print("  python runner.py --test-envelope <file>  # Testar envelope creation")
        sys.exit(1)

    # ── Default mode: build pipeline ──
    build_pipeline()


if __name__ == "__main__":
    main()
